#########################################
# peaklist - database miner to xlsx file#
#########################################

# This script takes an feateure list txt file who is comma separated
# there feature names and mz values will be noted down.
# on the MZ is a range in ppm difference available in the setting to search in between
# all found databases inside the folder to databases will be used
# databases have been generated by the MetaboShiny Github package and own pubchemParser
# all data is saved in the given excel file


################
# imports ######
################
import sqlite3
import os
import pip
pip.main(['install','xlsxwriter'])
import xlsxwriter



#############
# Variables##
#############

folder_to_databases = 'F:/avans/stage MM/databases/'
Variable_Metadata_path = 'F:/avans/stage MM/Sherloktest_data_3/SherLOKdata_processed_XCMS_IPO_fitgaus_2L/batch_correction/Variable_metaData_XCMS_IPO_fitgaus_2L.tsv_batchcorrected.tsv'
output_folder = "F:/avans/stage MM/Sherloktest_data_3/SherLOKdata_processed_XCMS_IPO_fitgaus_2L/batch_correction/"
ppm = 0.003
limit_output_query = 1



##################
# reading in data#
##################
mz_values = []

# reading in data
with open(Variable_Metadata_path, 'r') as f:
    for line in f:
        line = line.split('\t')
        print(line)
        # all feature names will be put in the possible result list to find out which fetures had no hit later on
        line = line[0:2]
        mz_values.append(line)



mz_values = mz_values[1:]


################################
# create output folder and name#
################################

if not(os.path.exists(output_folder)):
    os.mkdir(output_folder)

name = ((Variable_Metadata_path.split('/')[-1]).split('.'))[0]
outputlocation_and_name = output_folder + '/'+ name + '_ppm' + str(ppm) + '_' +'annotated.xlsx'

################################################
# check weither output file exsist if so rename#
################################################
if os.path.exists(outputlocation_and_name):
    outputlocation_and_name = ((outputlocation_and_name.split('.'))[0]) + '(1).xlsx'
    TMP_counter = 2
    while os.path.exists(outputlocation_and_name):
        outputlocation_and_name = (outputlocation_and_name.split('('))[0] + '(' + str(TMP_counter) + ').xlsx'
        TMP_counter += 1

#################
# Database check#
#################
TMP_databases = os.listdir(folder_to_databases)
databases = []
for item in TMP_databases:
    if item[-3:] == '.db':
        if 'extended' not in item:
            databases.append(item)

TMP_databases.clear()

####################################
# querying in the extended database#
####################################

# create te connection to extendend database
extended_database = folder_to_databases + 'extended.db'

workbook = xlsxwriter.Workbook(outputlocation_and_name)
worksheet = workbook.add_worksheet()

row = 0
column = 0

primal_header = ['Feature', 'inital_mz', 'found_mz','Delta_mz', 'fullformula', 'adduct', 'finalcharge', 'smiles', 'struct_id']
query_items = ['compoundname', 'description', 'baseformula', 'identifier', 'charge']
for item in primal_header:
    worksheet.write(row, column, item)
    column += 1

for database in databases:
    # column += 1
    database = database[:-3]
    query_items = (database + '.compound_name,' + database + '.description,' + database + '.baseformula,' + database + '.identifier,' + database + '.charge,').split(',')
    for item in query_items:
        column += 1
        worksheet.write(row, column, item)

# database connection
extended = sqlite3.connect(extended_database)
c = extended.cursor()

for item in mz_values:
    item_MZ = item[1]
    Feature = item[0]

    # the Query in the extended database
    query = 'SELECT extended.fullmz,' \
            'abs(' + str(float(item[1])) + ' - extended.fullmz) AS DELTA_MZ,'\
            ' extended.fullformula, extended.adduct, extended.finalcharge, structures.smiles, extended.struct_id FROM extended ' \
            'INNER JOIN structures ON extended.struct_id = structures.struct_id ' \
            'WHERE extended.fullmz >= ' + str(float(item[1]) - (ppm / 2)) + ' AND extended.fullmz <= ' + str(
            float(item[1]) + (ppm / 2)) + ' ORDER BY DELTA_MZ ASC ' \
            'LIMIT '+ str(limit_output_query) +';'

    # retrieve result in for loop becouse then it retrieve multiple results
    for hit in c.execute(query):
        # print(item)
        column = 2
        row += 1
        worksheet.write(row, 0, item[0])
        worksheet.write(row, 1, item[1])
        #worksheet.write(row, 2, max(float(item_MZ), float(hit[0])) - (min(float(item_MZ), float(hit[0]))))
        smiles = hit[-2]

        for item_a in hit:
            worksheet.write(row, column, item_a)
            column += 1




        # column += 1
        #column = 9
        counter = 0

        for database in databases:
            column += 1
            counter += 1
            database = folder_to_databases + database
            database_a = sqlite3.connect(database)
            C = database_a.cursor()
            query = ('SELECT compoundname, description, baseformula, identifier, charge FROM base '
                         ' WHERE structure = "' + smiles + '" '
                                                           ' LIMIT 10;')

            C.execute(query)
            data = C.fetchall()

            if len(data) == 0:
                for i in range(5):
                    worksheet.write(row, column, 'NA')
                    column += 1

            elif (len(data)) != 1:
                compound = ''
                description = ''
                baseformula = ''
                identifier = ''
                charge = ''
                for item_b in data:
                    compound = compound + '---' + str(item_b[0])
                    description = description + '---' + str(item_b[1])
                    baseformula = baseformula + '---' + str(item_b[2])
                    identifier = identifier + '---' + str(item_b[3])
                    charge = charge + '---' + str(item_b[4])

                data = [compound[3:], description[3:], baseformula[3:], identifier[3:], charge[3:]]

                for query_items in data:

                    if column / 6 == (1.5 + counter):
                        column += 1
                    worksheet.write(row, column, query_items)
                    column += 1

            else:
                for query_items in data:
                    if column / 6 == (1.5 + counter):
                        column += 1

                    for item_c in query_items:
                        if item_c == None:
                            worksheet.write(row, column, 'NA')

                        worksheet.write(row, column, item_c)
                        column += 1

workbook.close()
